[RN0.66] 12/n: Strip Flow types from Reanimated worklets
Summary:
The combination of React Native 0.66 and Reanimated 2.3 seems to have some issue with stripping Flow types from Reanimated worklets. I saw errors like the following before I stripped these types:

```
error: SyntaxError: /Users/ashoat/src/comm/native/chat/swipeable-message.react.js: /Users/ashoat/src/comm/native/chat/swipeable-message.react.js: Unexpected token, expected "," (2:35)

  1 |
> 2 | (function makeSpringConfig(velocity: number) {
    |                                    ^
  3 |   return {
  4 |     stiffness: 257.1370588235294,
  5 |     damping: 19.003038357561845,
```

Since most of the types weren't exported, I was actually able to remove their type annotations without issue. The only exception was `dividePastDistance`; to unblock ourselves there, since it was only used in `SwipeableMessage` I moved it into there.

Will track the higher-level investigation [here](https://linear.app/comm/issue/ENG-623/investigate-why-reanimated-23-is-failing-to-strip-flow-types) on Linear.

Test Plan: Built and ran the whole stack on iOS and Android across various architectures

Reviewers: karol-bisztyga, palys-swm, atul

Reviewed By: karol-bisztyga, palys-swm

Subscribers: benschac, Adrian

Differential Revision: https://phabricator.ashoat.com/D2991